import Head from 'next/head';
import Hero from "../components/Hero"

export default function About(props) {
  return (
    <>
      <div>
        <Head>
          <title>Victor Singh - About</title>
          <meta
            name="My portfolio website"
            content="Generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero
          heading="Thank you for your interest!"
          message="Below you can learn about me and why I am interested in programming."
        />
      </div>
    </>
  );
}
