import Head from 'next/head';
import Hero from "../components/Hero";

export default function Home() {
  return (
    <> 
    <div>
      <Head>
        <title>Victor Singh</title>
        <meta name='My portfolio website' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Hero heading="Welcome to my website!" message="The website is still under construction." button="Learn More"/>      
    </div>

    </>
  );
}
